# Generated by Django 3.0.2 on 2020-07-29 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='カード名')),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='デッキ名')),
                ('comment', models.TextField(blank=True, verbose_name='コメント')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to='cms.Card', verbose_name='カード')),
            ],
        ),
    ]
